### ISSUE TITLE
App crahes when ram is cleared

### ISSUE THREAD

**Issue by sachinsav** [FullBinaryAlchemist/SecurityApplication#62]
after successfull sign in or sign up if you directly clear the app from ram then it crashes ....it is not happening in all mobile but in some mobile it is crahing most probably due to services it is happening

**Comment by sachinsav** [comment]
in my emulator and my sumsung mobile it is crahing i have one more mobile of oppo in that it's not

**Comment by FullBinaryAlchemist** [comment]
Android Version and OS version of the devices on which you have tested. Also share the crash log @sachinsav

**Comment by FullBinaryAlchemist** [comment]
Checkout #71
