### ISSUE TITLE
Background SOS player fixing

### ISSUE THREAD

**Issue by FullBinaryAlchemist** [FullBinaryAlchemist/SecurityApplication#67]
- [x] The audio should be played speakers and headset.

- [x] The media volume should be fixed at MAX for the duration of playing

**Comment by FullBinaryAlchemist** [comment]
Used:https://stackoverflow.com/questions/6896746/is-there-a-broadcast-action-for-volume-changes

**Comment by sachinsav** [comment]
i can't able to control media volume even after pressing inform safety button and closing the app .
it come under my control after removing the app from ram

**Comment by sachinsav** [comment]
it is showing 3 sound track for volume of security application sometime it is showing less and sometime more too(i.e 5) in samsung galaxy j5

**Comment by FullBinaryAlchemist** [comment]
Current Issue:
1.If a call is received when the sos is playing then after the call  the audio will be routed through headphones if headphones were plugged in.
